name = "fantasy-command-center-api"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

# Build is handled by wrangler automatically

[[d1_databases]]
binding = "DB"
database_name = "fantasy_command_db"
database_id = "620d2c79-c751-4bdd-8ec4-afe56fc9b3a1"

[triggers]
crons = ["0 * * * *"] # hourly ingestion job

[vars]
NOAA_BASE_URL = "https://api.weather.gov"
ESPN_BASE_URL = "https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl" 